sonar.host.url=https://sonarqube.curatedcontraptions.com
sonar.projectKey=immersi-ads-android
sonar.projectName=ImmersiAds Android
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.tests=app/src/test/java
sonar.exclusions=app/src/test/**/*,app/build/**/*,.gradle/**/*,.scannerwork/**/*,gradle/**/*

sonar.sourceEncoding=UTF-8
sonar.java.coveragePlugin=jacoco

sonar.kotlin.appProjectPath=app
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/test/jacocoTestReport.xml
