sonar.projectKey=immersi-ads-android
sonar.projectName=ImmersiAds Android
sonar.projectVersion=1.0.0

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.java.binaries=app/build/intermediates/classes/debug
sonar.java.libraries=**/*.jar

sonar.sourceEncoding=UTF-8
sonar.java.coveragePlugin=jacoco

sonar.kotlin.appProjectPath=app
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/test/jacocoTestReport.xml
